name: Update README with GitHub Activity

on:
  schedule:
    - cron: "0 * * * *" # Executa a cada hora
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update README with recent GitHub activity
        uses: Readme-Workflows/recent-activity@v2
        with:
          GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
